# Generated by Django 3.2.8 on 2021-10-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
