# Generated by Django 3.2.8 on 2021-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
